export const apple_red_on_white = {
    "top-menu-bg": "#fff",
    "top-menu-color": "#4D4F53",
    "top-menu-color-active": "#fff",
    "top-menu-bg-active-primary": "#ED1C23",
    "top-menu-bg-active-secondary": "#D1151F",
    "agenda-list-title-color": "#4D4F53",
    "agenda-month-year-bg": "#ED1C23",
    "agenda-month-year-color": "#fff",
    "agenda-cell-bg": "#fff",
    "agenda-cell-color": "#0C0C0C",
    "agenda-cell-bg-hover": "#BDC1C8",
    "agenda-cell-color-hover": "#0C0C0C",
    "agenda-cell-bg-active": "#4D4F53",
    "agenda-cell-color-active": "#fff",
    "agenda-cell-today-bg": "#fff",
    "agenda-cell-today-color": "#ED1C23",
    "mw-legend-bg": "#BDC1C8",
    "mw-legend-color": "#0C0C0C",
    "mw-legend-today-bg": "#ED1C23",
    "mw-legend-today-color": "#fff",
    "mw-cell-bg": "#fff",
    "mw-cell-color": "#0C0C0C",
    "mw-cell-bg-hover": "#BDC1C8",
    "mw-cell-color-hover": "#0C0C0C",
    "mw-cell-bg-active": "#4D4F53",
    "mw-cell-color-active": "#fff",
    "mw-cell-diff-bg": "#f5f5f5",
    "mw-cell-diff-color": "#4D4F53",
    "mw-cell-today-bg": "#ED1C23",
    "mw-cell-today-color": "#fff",
    "grid-bg": "#fff",
    "grid-border-color": "#efefef",
    "grid-title-color": "#4D4F53",
    "grid-text-color": "#0C0C0C",
    "boxgrid-title-color": "#fff",
    "boxgrid-text-color": "#fff",
    "ep-bg": "#fff",
    "ep-bg-hover": "#BDC1C8",
    "ep-title-color": "#4D4F53",
    "ep-title-color-hover": "#4D4F53",
    "ep-text-color": "#4D4F53",
    "ep-text-color-hover": "#4D4F53",
    "ep-button-color": "#4D4F53",
    "ep-button-color-hover": "#ED1C23",
    "ec-bg": "#fff",
    "ec-title-color": "#4D4F53",
    "ec-title-secondary-color": "#4D4F53",
    "ec-text-color": "#0C0C0C",
    "ec-tab-menu-bg": "#BDC1C8",
    "ec-tab-menu-bg-active": "#fff",
    "ec-tab-menu-color": "#4D4F53",
    "ec-tab-menu-color-active": "#4D4F53",
    "ec-button-bg": "#4D4F53",
    "ec-button-bg-hover": "#ED1C23",
    "ec-button-color": "#fff",
    "ec-button-color-hover": "#fff",
    "ec-button-toggle-color": "#4D4F53",
    "ec-button-toggle-color-hover": "#ED1C23"
}

export const orange_on_dark_gray = {
    "top-menu-bg": "#464646",
    "top-menu-color": "#fff",
    "top-menu-color-active": "#fff",
    "top-menu-bg-active-primary": "#ff7900",
    "top-menu-bg-active-secondary": "#EC5025",
    "agenda-list-title-color": "#fff",
    "agenda-month-year-bg": "#F79021",
    "agenda-month-year-color": "#fff",
    "agenda-cell-bg": "#464646",
    "agenda-cell-color": "#fff",
    "agenda-cell-bg-hover": "#f2ad72",
    "agenda-cell-color-hover": "#fff",
    "agenda-cell-bg-active": "#EC5025",
    "agenda-cell-color-active": "#fff",
    "agenda-cell-today-bg": "#464646",
    "agenda-cell-today-color": "#F79021",
    "mw-legend-bg": "#464646",
    "mw-legend-color": "#fff",
    "mw-legend-today-bg": "#464646",
    "mw-legend-today-color": "#f2ad72",
    "mw-cell-bg": "#464646",
    "mw-cell-color": "#fff",
    "mw-cell-bg-hover": "#f2ad72",
    "mw-cell-color-hover": "#fff",
    "mw-cell-bg-active": "#EC5025",
    "mw-cell-color-active": "#fff",
    "mw-cell-diff-bg": "#606060",
    "mw-cell-diff-color": "#fff",
    "mw-cell-today-bg": "#F79021",
    "mw-cell-today-color": "#fff",
    "grid-bg": "#464646",
    "grid-border-color": "#383838",
    "grid-title-color": "#fff",
    "grid-text-color": "#d9d9d9",
    "boxgrid-title-color": "#fff",
    "boxgrid-text-color": "#fff",
    "ep-bg": "#464646",
    "ep-bg-hover": "#606060",
    "ep-title-color": "#fff",
    "ep-title-color-hover": "#fff",
    "ep-text-color": "#d9d9d9",
    "ep-text-color-hover": "#d9d9d9",
    "ep-button-color": "#fff",
    "ep-button-color-hover": "#f2ad72",
    "ec-bg": "#464646",
    "ec-title-color": "#fff",
    "ec-title-secondary-color": "#fff",
    "ec-text-color": "#d9d9d9",
    "ec-tab-menu-bg": "#464646",
    "ec-tab-menu-bg-active": "#F79021",
    "ec-tab-menu-color": "#fff",
    "ec-tab-menu-color-active": "#fff",
    "ec-button-bg": "#ff7900",
    "ec-button-bg-hover": "#f9a952",
    "ec-button-color": "#fff",
    "ec-button-color-hover": "#fff",
    "ec-button-toggle-color": "#fff",
    "ec-button-toggle-color-hover": "#f9a952"
}

export const autumn_theme_on_white = {
    "top-menu-bg": "#fff",
    "top-menu-color": "#52565E",
    "top-menu-color-active": "#fff",
    "top-menu-bg-active-primary": "#F2AE72",
    "top-menu-bg-active-secondary": "#da645a",

    "agenda-list-title-color": "#52565E",
    "agenda-month-year-bg": "#578b74",
    "agenda-month-year-color": "#fff",
    "agenda-cell-bg": "#fff",
    "agenda-cell-color": "#52565E",
    "agenda-cell-bg-hover": "#F2AE72",
    "agenda-cell-color-hover": "#fff",
    "agenda-cell-bg-active": "#D96459",
    "agenda-cell-color-active": "#fff",
    "agenda-cell-today-bg": "#fff",
    "agenda-cell-today-color": "#da645a",
    "mw-legend-bg": "#588C73",
    "mw-legend-color": "#fff",
    "mw-legend-today-bg": "#F2AE72",
    "mw-legend-today-color": "#D96459",
    "mw-cell-bg": "#fff",
    "mw-cell-color": "#52565E",
    "mw-cell-bg-hover": "#F2AE72",
    "mw-cell-color-hover": "#fff",
    "mw-cell-bg-active": "#da645a",
    "mw-cell-color-active": "#fff",
    "mw-cell-diff-bg": "#f3f4f7",
    "mw-cell-diff-color": "#aaaaaa",
    "mw-cell-today-bg": "#F2AE72",
    "mw-cell-today-color": "#da645a",
    "grid-bg": "#fff",
    "grid-border-color": "#ebebeb",
    "grid-title-color": "#52565E",
    "grid-text-color": "#52565E",
    "boxgrid-title-color": "#fff",
    "boxgrid-text-color": "#fff",
    "ep-bg": "#fff",
    "ep-bg-hover": "#ebebeb",
    "ep-title-color": "#52565E",
    "ep-title-color-hover": "#52565E",
    "ep-text-color": "#52565E",
    "ep-text-color-hover": "#52565E",
    "ep-button-color": "#52565E",
    "ep-button-color-hover": "#578b74",
    "ec-bg": "#fff",
    "ec-title-color": "#52565E",
    "ec-title-secondary-color": "#52565E",
    "ec-text-color": "#52565E",
    "ec-tab-menu-bg": "#ebebeb",
    "ec-tab-menu-bg-active": "#F2AE72",
    "ec-tab-menu-color": "#52565E",
    "ec-tab-menu-color-active": "#fff",
    "ec-button-bg": "#da645a",
    "ec-button-bg-hover": "#F2AE72",
    "ec-button-color": "#fff",
    "ec-button-color-hover": "#fff",
    "ec-button-toggle-color": "#fff",
    "ec-button-toggle-color-hover": "#F2AE72"
}

export const yellow_on_white = {
    "top-menu-bg": "#fff",
    "top-menu-color": "#505050",
    "top-menu-color-active": "#fff",
    "top-menu-bg-active-primary": "#FFC068",
    "top-menu-bg-active-secondary": "#F69753",

    "agenda-list-title-color": "#505050",
    "agenda-month-year-bg": "#FFC068",
    "agenda-month-year-color": "#fff",
    "agenda-cell-bg": "#fff",
    "agenda-cell-color": "#505050",
    "agenda-cell-bg-hover": "#FFC068",
    "agenda-cell-color-hover": "#fff",
    "agenda-cell-bg-active": "#F69753",
    "agenda-cell-color-active": "#fff",
    "agenda-cell-today-bg": "#fff",
    "agenda-cell-today-color": "#F69753",

    "mw-legend-bg": "#505050",
    "mw-legend-color": "#fff",
    "mw-legend-today-bg": "#505050",
    "mw-legend-today-color": "#FFC068",
    "mw-cell-bg": "#fff",
    "mw-cell-color": "#505050",
    "mw-cell-bg-hover": "#FFC068",
    "mw-cell-color-hover": "#fff",
    "mw-cell-bg-active": "#F69753",
    "mw-cell-color-active": "#fff",
    "mw-cell-diff-bg": "#E5E5E5",
    "mw-cell-diff-color": "#505050",
    "mw-cell-today-bg": "#F69753",
    "mw-cell-today-color": "#fff",

    "grid-bg": "#fff",
    "grid-border-color": "#ebebeb",
    "grid-title-color": "#505050",
    "grid-text-color": "#505050",

    "boxgrid-title-color": "#fff",
    "boxgrid-text-color": "#fff",

    "ep-bg": "#fff",
    "ep-bg-hover": "#E5E5E5",
    "ep-title-color": "#505050",
    "ep-title-color-hover": "#505050",
    "ep-text-color": "#505050",
    "ep-text-color-hover": "#505050",
    "ep-button-color": "#505050",
    "ep-button-color-hover": "#F69753",

    "ec-bg": "#fff",
    "ec-title-color": "#505050",
    "ec-title-secondary-color": "#505050",
    "ec-text-color": "#505050",
    "ec-tab-menu-bg": "#ebebeb",
    "ec-tab-menu-bg-active": "#FFC068",
    "ec-tab-menu-color": "#505050",
    "ec-tab-menu-color-active": "#fff",
    "ec-button-bg": "#da645a",
    "ec-button-bg-hover": "#FFC068",
    "ec-button-color": "#fff",
    "ec-button-color-hover": "#fff",
    "ec-button-toggle-color": "#fff",
    "ec-button-toggle-color-hover": "#FFC068"
}

export const green_on_white = {
    "top-menu-bg": "#fff",
    "top-menu-color": "#505050",
    "top-menu-color-active": "#fff",
    "top-menu-bg-active-primary": "#8DC06C",
    "top-menu-bg-active-secondary": "#537B35",

    "agenda-list-title-color": "#505050",
    "agenda-month-year-bg": "#8DC06C",
    "agenda-month-year-color": "#fff",
    "agenda-cell-bg": "#fff",
    "agenda-cell-color": "#505050",
    "agenda-cell-bg-hover": "#8DC06C",
    "agenda-cell-color-hover": "#fff",
    "agenda-cell-bg-active": "#537B35",
    "agenda-cell-color-active": "#fff",
    "agenda-cell-today-bg": "#fff",
    "agenda-cell-today-color": "#537B35",

    "mw-legend-bg": "#505050",
    "mw-legend-color": "#fff",
    "mw-legend-today-bg": "#505050",
    "mw-legend-today-color": "#8DC06C",
    "mw-cell-bg": "#fff",
    "mw-cell-color": "#505050",
    "mw-cell-bg-hover": "#8DC06C",
    "mw-cell-color-hover": "#fff",
    "mw-cell-bg-active": "#537B35",
    "mw-cell-color-active": "#fff",
    "mw-cell-diff-bg": "#f3f4f7",
    "mw-cell-diff-color": "#aaaaaa",
    "mw-cell-today-bg": "#537B35",
    "mw-cell-today-color": "#fff",

    "grid-bg": "#fff",
    "grid-border-color": "#ebebeb",
    "grid-title-color": "#505050",
    "grid-text-color": "#505050",

    "boxgrid-title-color": "#fff",
    "boxgrid-text-color": "#fff",

    "ep-bg": "#fff",
    "ep-bg-hover": "#f3f4f7",
    "ep-title-color": "#505050",
    "ep-title-color-hover": "#505050",
    "ep-text-color": "#505050",
    "ep-text-color-hover": "#505050",
    "ep-button-color": "#505050",
    "ep-button-color-hover": "#537B35",

    "ec-bg": "#fff",
    "ec-title-color": "#505050",
    "ec-title-secondary-color": "#505050",
    "ec-text-color": "#505050",
    "ec-tab-menu-bg": "#ebebeb",
    "ec-tab-menu-bg-active": "#8DC06C",
    "ec-tab-menu-color": "#505050",
    "ec-tab-menu-color-active": "#fff",
    "ec-button-bg": "#da645a",
    "ec-button-bg-hover": "#8DC06C",
    "ec-button-color": "#fff",
    "ec-button-color-hover": "#fff",
    "ec-button-toggle-color": "#fff",
    "ec-button-toggle-color-hover": "#8DC06C"
}

export const violet_on_white = {
    "top-menu-bg": "#fff",
    "top-menu-color": "#505050",
    "top-menu-color-active": "#fff",
    "top-menu-bg-active-primary": "#8D43E7",
    "top-menu-bg-active-secondary": "#B84592",

    "agenda-list-title-color": "#505050",
    "agenda-month-year-bg": "#8D43E7",
    "agenda-month-year-color": "#fff",
    "agenda-cell-bg": "#fff",
    "agenda-cell-color": "#505050",
    "agenda-cell-bg-hover": "#8D43E7",
    "agenda-cell-color-hover": "#fff",
    "agenda-cell-bg-active": "#B84592",
    "agenda-cell-color-active": "#fff",
    "agenda-cell-today-bg": "#fff",
    "agenda-cell-today-color": "#B84592",

    "mw-legend-bg": "#505050",
    "mw-legend-color": "#fff",
    "mw-legend-today-bg": "#B84592",
    "mw-legend-today-color": "#fff",

    "mw-cell-bg": "#fff",
    "mw-cell-color": "#505050",
    "mw-cell-bg-hover": "#8D43E7",
    "mw-cell-color-hover": "#fff",
    "mw-cell-bg-active": "#B84592",
    "mw-cell-color-active": "#fff",
    "mw-cell-diff-bg": "#f3f4f7",
    "mw-cell-diff-color": "#aaaaaa",
    "mw-cell-today-bg": "#B84592",
    "mw-cell-today-color": "#fff",

    "grid-bg": "#fff",
    "grid-border-color": "#ebebeb",
    "grid-title-color": "#505050",
    "grid-text-color": "#505050",

    "boxgrid-title-color": "#fff",
    "boxgrid-text-color": "#fff",

    "ep-bg": "#fff",
    "ep-bg-hover": "#f3f4f7",
    "ep-title-color": "#505050",
    "ep-title-color-hover": "#505050",
    "ep-text-color": "#505050",
    "ep-text-color-hover": "#505050",
    "ep-button-color": "#505050",
    "ep-button-color-hover": "#B84592",

    "ec-bg": "#fff",
    "ec-title-color": "#505050",
    "ec-title-secondary-color": "#505050",
    "ec-text-color": "#505050",
    "ec-tab-menu-bg": "#ebebeb",
    "ec-tab-menu-bg-active": "#8D43E7",
    "ec-tab-menu-color": "#505050",
    "ec-tab-menu-color-active": "#fff",
    "ec-button-bg": "#da645a",
    "ec-button-bg-hover": "#8D43E7",
    "ec-button-color": "#fff",
    "ec-button-color-hover": "#fff",
    "ec-button-toggle-color": "#fff",
    "ec-button-toggle-color-hover": "#8D43E7"
}

export const mono = {
    'top-menu-bg': '#fff',
    'top-menu-color': '#202020',
    'top-menu-color-active': '#fff',
    'top-menu-bg-active-primary': '#202020',
    'top-menu-bg-active-secondary': '#606060',

    'agenda-list-title-color': '#202020',
    'agenda-month-year-bg': '#202020',
    'agenda-month-year-color': '#fff',
    'agenda-cell-bg': '#fff',
    'agenda-cell-color': '#202020',
    'agenda-cell-bg-hover': '#ececec',
    'agenda-cell-color-hover': '#202020',
    'agenda-cell-bg-active': '#202020',
    'agenda-cell-color-active': '#fff',
    'agenda-cell-today-bg': '#fff',
    'agenda-cell-today-color': '#202020',

    'mw-legend-bg': '#606060',
    'mw-legend-color': '#fff',
    'mw-legend-today-bg': '#202020',
    'mw-legend-today-color': '#fff',

    'mw-cell-bg': '#fff',
    'mw-cell-color': '#202020',
    'mw-cell-bg-hover': '#ececec',
    'mw-cell-color-hover': '#202020',
    'mw-cell-bg-active': '#202020',
    'mw-cell-color-active': '#fff',
    'mw-cell-diff-bg': '#f5f5f5',
    'mw-cell-diff-color': '#202020',
    'mw-cell-today-bg': '#202020',
    'mw-cell-today-color': '#fff',

    'grid-bg': '#fff',
    'grid-border-color': '#ececec',
    'grid-title-color': '#202020',
    'grid-text-color': '#525252',

    'boxgrid-title-color': '#fff',
    'boxgrid-text-color': '#fff',

    'ep-bg': '#fff',
    'ep-bg-hover': '#ececec',
    'ep-title-color': '#202020',
    'ep-title-color-hover': '#202020',
    'ep-text-color': '#525252',
    'ep-text-color-hover': '#525252',
    'ep-button-color': '#202020',
    'ep-button-color-hover': '#202020',

    'ec-bg': '#fff',
    'ec-title-color': '#202020',
    'ec-title-secondary-color': '#202020',
    'ec-text-color': '#525252',

    'ec-tab-menu-bg': '#ececec',
    'ec-tab-menu-bg-active': '#fff',
    'ec-tab-menu-color': '#202020',
    'ec-tab-menu-color-active': '#202020',

    'ec-button-bg': '#202020',
    'ec-button-bg-hover': '#606060',
    'ec-button-color': '#fff',
    'ec-button-color-hover': '#fff',
    'ec-button-toggle-color': '#202020',
    'ec-button-toggle-color-hover': '#202020',
}

export const default_theme = {
    'top-menu-bg': '#fff',
    'top-menu-color': '#525252',
    'top-menu-color-active': '#fff',
    'top-menu-bg-active-primary': '#ff5f5f',
    'top-menu-bg-active-secondary': '#eb4b4b',

    'agenda-list-title-color': '#202020',
    'agenda-month-year-bg': '#ececec',
    'agenda-month-year-color': '#202020',
    'agenda-cell-bg': '#fff',
    'agenda-cell-color': '#202020',
    'agenda-cell-bg-hover': '#ececec',
    'agenda-cell-color-hover': '#202020',
    'agenda-cell-bg-active': '#202020',
    'agenda-cell-color-active': '#fff',
    'agenda-cell-today-bg': '#fff',
    'agenda-cell-today-color': '#ff5f5f',

    'mw-legend-bg': '#202020',
    'mw-legend-color': '#bdc0c8',
    'mw-legend-today-bg': '#2c2e32',
    'mw-legend-today-color': '#f6bf64',

    'mw-cell-bg': '#fff',
    'mw-cell-color': '#202020',
    'mw-cell-bg-hover': '#ececec',
    'mw-cell-color-hover': '#202020',
    'mw-cell-bg-active': '#202020',
    'mw-cell-color-active': '#fff',
    'mw-cell-diff-bg': '#f5f5f5',
    'mw-cell-diff-color': '#202020',
    'mw-cell-today-bg': '#ff5f5f',
    'mw-cell-today-color': '#fff',

    'grid-bg': '#fff',
    'grid-border-color': '#efefef',
    'grid-title-color': '#202020',
    'grid-text-color': '#525252',

    'boxgrid-title-color': '#fff',
    'boxgrid-text-color': '#fff',

    'ep-bg': '#fff',
    'ep-bg-hover': '#ececec',
    'ep-title-color': '#202020',
    'ep-title-color-hover': '#525252',
    'ep-text-color': '#525252',
    'ep-text-color-hover': '#525252',
    'ep-button-color': '#202020',
    'ep-button-color-hover': '#ff5f5f',

    'ec-bg': '#fff',
    'ec-title-color': '#202020',
    'ec-title-secondary-color': '#202020',
    'ec-text-color': '#525252',

    'ec-tab-menu-bg': '#ececec',
    'ec-tab-menu-bg-active': '#fff',
    'ec-tab-menu-color': '#525252',
    'ec-tab-menu-color-active': '#525252',

    'ec-button-bg': '#202020',
    'ec-button-bg-hover': '#ff5f5f',
    'ec-button-color': '#fff',
    'ec-button-color-hover': '#fff',
    'ec-button-toggle-color': '#202020',
    'ec-button-toggle-color-hover': '#ff5f5f',
}